version: '3.8'

services:
  ui-service:
    build: ./ui
    env_file: .env
    restart: unless-stopped
    volumes:
      - ./ui:/app  # Mount the application code
    networks:
      - backend
    stop_signal: SIGINT
    ports:
      - "3000:3000"

  llm-service:
    build: ./langchain
    env_file: .env
    restart: unless-stopped
    environment:
      - FLASK_ENV=development # Autorestarts flask when code changes are detected
    volumes:
    - ./langchain:/app  # Mount the application code
    networks:
      - backend
    stop_signal: SIGINT
    ports:
      - "3001:3001"

#  timeseries-service:
#    build: ./timeseries
#    env_file: .env
#    restart: unless-stopped
#    environment:
#      - FLASK_ENV=development # Autorestarts flask when code changes are detected
#    volumes:
#      - ./timeseries:/app  # Mount the application code
#    networks:
#      - backend
#    stop_signal: SIGINT
#    ports:
#      - "3002:3002"

#  database-service:
#    image: mongo:latest
#    restart: unless-stopped
#    networks:
#     - backend
#    volumes: 
#      - ./mongodb/data:/data/db
#    ports:
#      - "27017:27017"

networks:
  backend:
    driver: bridge